In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"priyambanerjee2005","key":"ca4f015ebcc27b16a6234e316eac9db1"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 38.5MB/s]

In [ ]:
import zipfile

In [ ]:
with zipfile.ZipFile('bengaluru-house-price-dataset.zip') as z:
  z.extractall("House")

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/House/bengaluru_house_prices.csv")
df=pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
df.isnull().sum().sum()

np.int64(6201)

In [ ]:
df.size

119880

In [ ]:
df1_1=df.dropna()
df1_1.size

67464

In [ ]:
df_2=df.fillna(100)
df_2.size

119880

In [ ]:
df.shape

(13320, 9)

In [ ]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [ ]:
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [ ]:
df.drop('column_name', axis=1, inplace=True)

KeyError: "['column_name'] not found in axis"

In [ ]:
cat_col=df.select_dtypes(include=['object']).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'society', 'total_sqft']

In [ ]:
num_col=df.select_dtypes(include=['int64','float64']).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [ ]:
from sklearn.impute  import SimpleImputer

In [ ]:
cat_clean=SimpleImputer(strategy='most_frequent')
num_clean=SimpleImputer(strategy='mean')

In [ ]:
df.cat_col=cat_clean.fit_transform(df[cat_col])
df.num_col=num_clean.fit_transform(df[num_col])

/tmp/ipykernel_4774/2382725948.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.cat_col=cat_clean.fit_transform(df[cat_col])
/tmp/ipykernel_4774/2382725948.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.num_col=num_clean.fit_transform(df[num_col])

In [ ]:
df.isnull().sum().sum()

np.int64(6201)

In [ ]:
df.size

119880

In [ ]:
df["size"]=df["size"].astype(str)
a=df["size"].apply(lambda x:int(x.split(" ")[0]) if x!="nan" else np.nan)
df["size"]=a
a

0        2.0
1        4.0
2        3.0
3        3.0
4        2.0
        ...
13315    5.0
13316    4.0
13317    2.0
13318    4.0
13319    1.0
Name: size, Length: 13320, dtype: float64